export const STANDARD = {
  kitchen: {
    title: "Kitchen",
    items: [
      "High dust covering",
      "Light fixtures",
      "Mid-level dust, pictures, switches, skirting's, etc.",
      "Clean/dust blinds",
      "Clean dust ledges, doors, handles, etc.",
      "Clean/polish tiles, worktops",
      "Clean/polish cupboard doors, drawers, and handles",
      "Clean fridge, freezer, dishwasher, oven front",
      "Empty and wash wastebin, replace liner",
      "Clean/polish sink area",
      "Glass and mirrors polished",
      "Vacuum/sweep and mop floor",
    ],
  },
  bathroom: {
    title: "Bathrooms",
    items: [
      "High dust covering, light fittings, etc.",
      "Low dust pictures, switches, skirtings, etc.",
      "Clean/dust blinds",
      "Clean ledges, doors, handles, etc.",
      "Clean/polish all tiled areas and worktops",
      "Clean toilet, bath, shower, and sink (including outside and plugs)",
      "Glass and mirrors polished",
      "Empty and wash waste bin",
      "Vacuum flooring and mop",
      "Bath panels cleaned/dusted",
    ],
  },
  bedroom: {
    title: "Bedrooms",
    items: [
      "High dust covering, light fittings, etc.",
      "Low dust pictures, switches, skirtings, etc.",
      "Clean/dust blinds",
      "Clean/dust ledges, furniture, doors, handles, etc.",
      "Change/straighten bed and dust headboard",
      "Move bedside to clean behind",
      "Clean all toiletries on the dressing table",
      "Glass and mirror-polished",
      "Empty any bins",
      "Vacuum flooring and mop",
    ],
  },
  livingRoom: {
    title: "Living Room / Dining Room / Office",
    items: [
      "High dust covering, light fittings, etc.",
      "Low dust pictures, switches, skirtings, etc.",
      "Clean/dust blinds",
      "Clean/dust ledges, furniture, doors, handles, etc.",
      "The sofa was wiped down/tidied",
      "Fireplace cleaned",
      "Glass and mirrors polished",
      "Empty any bins trash/recycling",
      "Vacuum flooring and mop",
    ],
  },
};
